### ISSUE TITLE
正常关闭的信息提示

### ISSUE THREAD

**Issue by mia0x75** [jilieryuyi/wing-binlog-go#34]
用-stop关闭

```
INFO[2017-12-15] closing canal                                
INFO[2017-12-15] syncer is closing...                         
WARN[2017-12-15] tcp服务发生错误：accept tcp [::]:9998: use of closed network connection 
WARN[2017-12-15] tcp服务发生错误：accept tcp [::]:9998: use of closed network connection 
WARN[2017-12-15] tcp服务发生错误：accept tcp [::]:9998: use of closed network connection 
ERRO[2017-12-15] canal start sync binlog err: context canceled 
FATA[2017-12-15] binlog服务：start canal err context canceled
```

这个是不是不应该有WARN/ERRO/FATA类的错误信息？

**Comment by jilieryuyi** [comment]
这个问题处理过了，更新一下

**Comment by mia0x75** [comment]
https://github.com/jilieryuyi/wing-binlog-go/commit/a3e83e1e921cf2bbf8aa6892aa575f605ce62b47

这个commit？我觉得是否只应该有INFO类的消息，比如类似这样

INFO [yyyy-MM-dd] 关闭Canal
INFO [yyyy-MM-dd] 等待队列处理完成
INFO [yyyy-MM-dd] 关闭TCP连接
INFO [yyyy-MM-dd] 关闭TCP服务
INFO [yyyy-MM-dd] 服务退出


然后删除pid，删除sock文件，等其他的一些清理，mysqld也是这么做的。

**Comment by jilieryuyi** [comment]
log.Warn("binlog服务：start canal err %v", err) 这里修改一下文案就可以了 “wing-binlog service exit：%+v”

**Comment by jilieryuyi** [comment]
这个做了相应的优化

**Comment by jilieryuyi** [comment]
1、关闭go-mysql停止接收数据
2、等待binlogcache写入完成
3、等待服务缓冲区数据发送完毕
4、退出服务

已优化

**Comment by mia0x75** [comment]
好像Ctrl+C或者-stop，还是有一些错误。现在还多了

github.com/siddontang/go-mysql/canal/sync.go:53: 
github.com/siddontang/go-mysql/canal/canal.go:203:

周一再重新编译测试。

**Comment by jilieryuyi** [comment]
github.com/siddontang/go-mysql/canal/sync.go:53:
github.com/siddontang/go-mysql/canal/canal.go:203:
这两个是go-mysql里面的，wing-binlog-go服务控制，调用close api都会报这个错误，忽略就可以了~

**Comment by jilieryuyi** [comment]
不会影响使用

**Comment by mia0x75** [comment]
tcp.enable = false

```
DEBU[2017-12-16 15:36:19] binlog服务退出...                                
INFO[2017-12-16 15:36:19] closing canal                                
DEBU[2017-12-16 15:36:19] http服务clientSendService退出：http://192.168.1.125:8001/index.php 
INFO[2017-12-16 15:36:19] syncer is closing...                         
ERRO[2017-12-16 15:36:19] canal start sync binlog err: context canceled 
INFO[2017-12-16 15:36:19] wing-binlog-go service exit: context canceled
github.com/siddontang/go-mysql/canal/sync.go:55: 
github.com/siddontang/go-mysql/canal/canal.go:203:  
ERRO[2017-12-16 15:36:19] connection was bad                           
ERRO[2017-12-16 15:36:19] close sync with err: Sync was closed         
INFO[2017-12-16 15:36:19] syncer is closed                             
DEBU[2017-12-16 15:36:19] binlog事件：OnPosSynced (mysql-bin.000348, 4) %!b(bool=true) 
DEBU[2017-12-16 15:36:19] binlog写入缓存：mysql-bin.000348:4:207673731      
DEBU[2017-12-16 15:36:19] 服务退出，等待SaveBinlogPostionCache完成，(mysql-bin.000348, 4) 
DEBU[2017-12-16 15:36:19] binlog-h.handler.Close退出...                  
DEBU[2017-12-16 15:36:19] binlog-h.BinlogHandler.cacheHandler 等待退出...  
DEBU[2017-12-16 15:36:19] binlog-h.BinlogHandler.cacheHandler.Close退出... 
DEBU[2017-12-16 15:36:19] 服务退出...                                      
DEBU[2017-12-16 15:36:19] tcp服务退出...                                   
DEBU[2017-12-16 15:36:19] tcp服务等待缓冲区数据发送完毕                             
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7b30df]

goroutine 1 [running]:
library/services.(*TcpService).Close(0xc4200d2600)
	/home/mxu/Downloads/src/github.com/jilieryuyi/wing-binlog-go/src/library/services/tcp.go:383 +0xef
library/binlog.(*Binlog).Close(0xc420178090)
	/home/mxu/Downloads/src/github.com/jilieryuyi/wing-binlog-go/src/library/binlog/binlog.go:112 +0x2a6
main.main()
	/home/mxu/Downloads/src/github.com/jilieryuyi/wing-binlog-go/src/wing-binlog-go/wing-binlog-go.go:153 +0x459
```

这几个看是否可以修复，或者给go-mysql提交一个PR。
ERRO[2017-12-16 15:36:19] canal start sync binlog err: context canceled 
INFO[2017-12-16 15:36:19] wing-binlog-go service exit: context canceled
github.com/siddontang/go-mysql/canal/sync.go:55: 
github.com/siddontang/go-mysql/canal/canal.go:203:  
ERRO[2017-12-16 15:36:19] connection was bad                           
ERRO[2017-12-16 15:36:19] close sync with err: Sync was closed

**Comment by jilieryuyi** [comment]
fix
